# Generated by Django 5.2.5 on 2025-11-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_availability_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='booked_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availability',
            name='is_vacation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='total_slots',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='availability',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
