# Generated by Django 5.2.5 on 2025-11-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_availability_booked_slots_availability_is_vacation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
