# Generated by Django 5.2.5 on 2025-09-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('counselor', 'Counselor'), ('admin', 'Admin')], default='user', max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer Not To Say')], max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('partner', 'Partner'), ('friend', 'Friend'), ('relative', 'Relative')], max_length=20, null=True)),
                ('accepted_privacy_policy', models.BooleanField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specializations', models.JSONField(blank=True, null=True)),
                ('other_specializations', models.TextField(blank=True, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('professional_id', models.FileField(blank=True, null=True, upload_to='professional_ids/')),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to='degree_certificates/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_accounts',
            },
        ),
    ]
